name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build binaries
    runs-on: windows-latest
    strategy:
      matrix:
        configuration:
          - Debug
          - Release
        include:
          - configuration: Debug
            preset: debug
          - configuration: Release
            preset: release
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1        

      - name: Build
        run: cmake --workflow --preset=${{matrix.preset}}

      - name: Upload ${{matrix.configuration}} binaries
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} binaries
          path: |
            build/${{matrix.preset}}/artifacts/w3m.exe
            build/${{matrix.preset}}/artifacts/w3m.pdb
