name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
    types: [opened, synchronize, reopened]
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        include:
          - configuration: Debug
            preset: debug
          - configuration: Release
            preset: release
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1.12.1        

      - name: CMake Build
        run: cmake --workflow --preset=${{matrix.preset}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} Artifacts
          path: |
            build/${{matrix.preset}}/artifacts/w3m.exe
            build/${{matrix.preset}}/artifacts/w3m.pdb
            build/${{matrix.preset}}/artifacts/server.exe
            build/${{matrix.preset}}/artifacts/server.pdb
    
  build-linux:
    name: Build Linux
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Release
        include:
          - configuration: Debug
            preset: debug
          - configuration: Release
            preset: release
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          submodules: true


      - name: Install GCC 11
        run: |
          sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
          sudo apt install -y g++-11

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: CMake Build
        run: cmake --workflow --preset=${{matrix.preset}}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.configuration}} Artifacts
          path: |
            build/${{matrix.preset}}/artifacts/server
